# Homework \#1 - Python exercise

In [1]:
import numpy as np

  Consider the following change of basis matrix in $\mathbb{C}^8$, with respect to the standard orthonormal basis:
  
  $$
      \mathbf{H} = \begin{bmatrix}
  1 & -1 & 0 & 0 & 0 & 0 & 0 & 0\\
  0 & 0 & 1 & -1 & 0 & 0 & 0 & 0\\
  0 & 0 & 0 & 0 & 1 & -1 & 0 & 0\\
  0 & 0 & 0 & 0 & 0 & 0 & 1 & -1\\
  1 & 1 & -1 & -1 & 0 & 0 & 0 & 0\\
  0 & 0 & 0 & 0 & 1 & 1 & -1 & -1\\
  1 & 1 & 1 & 1 & -1 & -1 & -1 & -1\\
  1 & 1 & 1 & 1 & 1 & 1 & 1 & 1\\
  \end{bmatrix}.
  $$
  
* What is an easy way to prove that the rows in $\mathbf{H}$ do indeed form a basis? (\emph{Hint}: it's enough to show that they are linearly independent, which is to say, that the matrix has full rank...)
* Use Python to verify point (a); obviously you can use \texttt{numpy}.


The basis described by $\mathbf{H}$ is called the \emph{Haar basis} and it is one of the most celebrated cornerstones of a branch of signal processing called wavelet analysis (which we won't study in this class). To get a feeling for its properties, however, consider the following set of Python experiments:

* Verify that $\mathbf{H}\mathbf{H}^H$ is a diagonal matrix, which means the vectors are orthogonal.
* Consider a constant signal $\mathbf{x} = \begin{bmatrix}1 & 1 & 1 & 1 & 1 & 1 & 1 & 1\end{bmatrix}$  and compute its coefficients in the Haar basis.
* Consider an alternating signal $\mathbf{y} = \begin{bmatrix}1 & -1 & 1 & -1 & 1 & -1 & 1 & -1\end{bmatrix}$ and compute its coefficients in the Haar basis.

In [2]:
# 8x8 Haar matrix
H = np.array([
    [1, -1,  0,  0,  0,  0,  0,  0],
    [0,  0,  1, -1,  0,  0,  0,  0],
    [0,  0,  0,  0,  1, -1,  0,  0],
    [0,  0,  0,  0,  0,  0,  1, -1],
    [1,  1, -1, -1,  0,  0,  0,  0],
    [0,  0,  0,  0,  1,  1, -1, -1],
    [1,  1,  1,  1, -1, -1, -1, -1],
    [1,  1,  1,  1,  1,  1,  1,  1]
])

In [3]:
# b) show that the rows are linearly independent
lambdas, V =  np.linalg.eig(H.T)
# The linearly dependent row vectors 
print(H[lambdas == 0,:])

# If it's an empty array, then the rows are linearly independent

[]


In [5]:
# c) verify that HH^T is diagonal

res = np.dot(H, H.T)

print(res)

[[2 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0]
 [0 0 0 2 0 0 0 0]
 [0 0 0 0 4 0 0 0]
 [0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 8]]


In [9]:
# d) compute a basis expansion
x = np.ones((8,1)) # note that we specify the shape to obtain a column vector

y = np.dot(H, x)

print(y)



[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [8.]]


In [17]:
# e) compute a basis expansion

x = np.array([[1], [-1], [1], [-1], [1], [-1], [1], [-1]]) # Alternating signal


y = np.dot(H, x)

print(y)



[[2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]]
